base:
is_dev : false
out_dir : ./model  # 输出目录
url_tag : json # web url tag(json,db(https://github.com/google/go-querystring))
language :  # 语言(English,中 文)
db_tag : gorm # 数据库标签(gorm,db)
singular_table : true  # 单表模式:true:禁用表名复数,false:采用表名复数 参考:gorm.SingularTable
simple : true # 简单输出(默认gorm标签不输出)
is_out_sql : false # 是否输出 sql 原信息
is_out_func : true # 是否输出 快捷函数
is_web_tag : true # 是否打web标记(json标记前提条件)
is_web_tag_pk_hidden: false # web标记是否隐藏主键
is_foreign_key : false # 是否导出外键关联
is_gui : false # 是否ui模式显示
is_table_name : false # 是否直接生成表名函数
is_null_to_point : false # 数据库默认 'DEFAULT NULL' 时设置结构为指针类型
db_info:
    host : 172.16.10.111 # type=1的时候，host为yml文件全路径
    port : 3306
    username : hnb
    password : alyHnb2015
    database : d_partner
    type: 0 # 数据库类型:0:mysql , 1:sqlite , 2:mssql
# sqlite
# db_info:
#     host : /Users/xxj/Downloads/caoguo # type=1的时候，host为yml文件全路径
#     port : 
#     username : 
#     password : 
#     database : 
#     type: 1 # 数据库类型:0:mysql , 1:sqlite , 2:mssql